"""
ProtonAI - Report Generators
Produces JSON and Markdown validation reports.
"""

from datetime import datetime
from pathlib import Path


class ReportGenerator:
    """Generates clinical-grade reports in JSON and Markdown formats."""

    def __init__(self, pipeline_version="1.0.0"):
        self.pipeline_version = pipeline_version
        self.timestamp = datetime.now().isoformat()

    def generate_json_report(self, validation_results, outlier_results, cross_errors, completeness, output_path=None):
        import json

        report = {
            "metadata": {
                "pipeline_version": self.pipeline_version,
                "generated_at": self.timestamp,
                "report_type": "clinical_data_validation"
            },
            "summary": {
                "total_records": completeness.get("total_rows", 0),
                "critical_errors": sum(1 for e in validation_results.get("errors", []) if e.get("level") == "critical"),
                "warnings": sum(1 for e in validation_results.get("errors", []) if e.get("level") == "warning"),
                "completeness_score": self._calc_completeness(completeness)
            },
            "completeness": completeness,
            "field_validation": validation_results,
            "outlier_detection": {k: {m: int(v.sum()) for m, v in methods.items()} for k, methods in outlier_results.items()},
            "cross_field_validation": cross_errors,
            "recommendations": self._generate_recommendations(validation_results, outlier_results, cross_errors, completeness)
        }

        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(report, f, indent=2, ensure_ascii=False, default=str)

        return report

    def generate_markdown_report(self, validation_results, outlier_results, cross_errors, completeness, output_path=None):
        md = f"""# ProtonAI Data Validation Report
**Generated:** {self.timestamp} | **Pipeline:** {self.pipeline_version}

## Executive Summary
| Metric | Value |
|--------|-------|
| Total Records | {completeness.get('total_rows', 0):,} |
| Critical Errors | {sum(1 for e in validation_results.get('errors', []) if e.get('level') == 'critical')} |
| Warnings | {sum(1 for e in validation_results.get('errors', []) if e.get('level') == 'warning')} |
| Completeness Score | {self._calc_completeness(completeness):.1f}% |

## Data Completeness
| Field | Status | Missing | % |
|-------|--------|---------|---|
"""
        for name, info in completeness.get("fields", {}).items():
            emoji = "✅" if info["status"] == "complete" else "⚠️" if info["status"] in ["warning", "acceptable"] else "❌"
            md += f"| `{name}` | {emoji} {info['status']} | {info['missing_count']} | {info['missing_pct']}% |\n"

        md += "\n## Field Validation\n"
        if validation_results.get("errors"):
            md += "### Errors Found\n| Row | Field | Level | Message | Value |\n|-----|-------|-------|---------|-------|\n"
            for e in validation_results["errors"][:50]:
                md += f"| {e.get('row','-')} | `{e.get('field','-')}` | {e.get('level','-')} | {e.get('message','-')} | {str(e.get('value','-'))[:30]} |\n"
            if len(validation_results["errors"]) > 50:
                md += f"\n> Showing 50 of {len(validation_results['errors'])} errors. See JSON for full details.\n"
        else:
            md += "✅ **No field validation errors.**\n"

        md += "\n## Outlier Detection\n| Field | IQR | Z-Score | Modified Z |\n|-------|-----|---------|------------|\n"
        for col, methods in outlier_results.items():
            md += f"| `{col}` | {int(methods['iqr'].sum())} | {int(methods['zscore'].sum())} | {int(methods['modified_zscore'].sum())} |\n"

        md += "\n## Cross-Field Validation\n"
        if cross_errors:
            md += "| Row | Type | Severity | Message |\n|-----|------|----------|---------|\n"
            for e in cross_errors:
                md += f"| {e.get('row','-')} | {e.get('type','-')} | {e.get('severity','-')} | {e.get('message','-')} |\n"
        else:
            md += "✅ **No cross-field inconsistencies.**\n"

        md += "\n## Recommendations\n"
        for i, rec in enumerate(self._generate_recommendations(validation_results, outlier_results, cross_errors, completeness), 1):
            emoji = "🔴" if rec.get("priority") == "high" else "🟡" if rec.get("priority") == "medium" else "🟢"
            md += f"{i}. {emoji} **{rec['title']}**  \n   {rec['description']}\n\n"

        md += "\n---\n*Auto-generated by ProtonAI Data Validation Pipeline*"

        if output_path:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(md)

        return md

    def _calc_completeness(self, completeness):
        fields = completeness.get("fields", {})
        if not fields:
            return 0.0
        scores = []
        for info in fields.values():
            scores.append(100 - info.get("missing_pct", 0) if info.get("present") else 0)
        return sum(scores) / len(scores) if scores else 0.0

    def _generate_recommendations(self, validation_results, outlier_results, cross_errors, completeness):
        recs = []
        incomplete = [n for n, i in completeness.get("fields", {}).items() if i.get("status") in ["warning", "critical", "missing_column"]]
        if incomplete:
            recs.append({"priority": "high", "title": "Improve Data Completeness", "description": f"Fields requiring attention: {', '.join(incomplete)}. Missing clinical data impacts predictive model accuracy."})

        critical = sum(1 for e in validation_results.get("errors", []) if e.get("level") == "critical")
        if critical > 0:
            recs.append({"priority": "high", "title": "Fix Critical Errors", "description": f"{critical} critical errors prevent production use. Must be resolved before model training."})

        total_outliers = sum(m["iqr"].sum() for m in outlier_results.values())
        if total_outliers > 10:
            recs.append({"priority": "medium", "title": "Review Outliers", "description": f"{int(total_outliers)} potential outliers detected. Clinical review recommended."})

        if cross_errors:
            recs.append({"priority": "medium", "title": "Resolve Cross-Field Inconsistencies", "description": f"{len(cross_errors)} inconsistencies found (e.g., dose/fraction mismatch)."})

        return recs
