"""D3: end-to-end dry-run pipeline (validator -> seal -> register -> v5 draft).

Proves the real-data path works before first patient. Writes a SEPARATE
RPT-001-V5-DRAFT.md (never touches EXPERIMENT_REPORT.md v4.0, keeping the
release gate and B5 safety guards intact). Aborts on validator REJECT.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

import pydicom
from pydicom.dataset import FileDataset, FileMetaDataset

from tools.real_data_validator import CT_SOP, RT_SOP, validate_series

ROOT = Path(__file__).resolve().parent.parent
DRAFT = ROOT / "docs" / "product" / "RPT-001-V5-DRAFT.md"


def build_synthetic_series(dir, n=3, name="", contours=True):
    dir = Path(dir); dir.mkdir(parents=True, exist_ok=True)
    for i in range(n):
        meta = FileMetaDataset()
        meta.MediaStorageSOPClassUID = CT_SOP
        meta.TransferSyntaxUID = "1.2.840.10008.1.2"
        ds = FileDataset(str(dir / f"{i}.dcm"), {}, file_meta=meta,
                         preamble=b"\0" * 128)
        ds.SOPClassUID = CT_SOP; ds.Modality = "CT"; ds.PatientName = name
        ds.ImagePositionPatient = [0, 0, i * 2.0]
        ds.PixelSpacing = [1.0, 1.0]; ds.RescaleIntercept = 0
        ds.save_as(str(dir / f"{i}.dcm"))
    if contours:
        meta = FileMetaDataset(); meta.TransferSyntaxUID = "1.2.840.10008.1.2"
        r = FileDataset(str(dir / "rt.dcm"), {}, file_meta=meta,
                        preamble=b"\0" * 128)
        r.SOPClassUID = RT_SOP; r.Modality = "RTSTRUCT"
        r.save_as(str(dir / "rt.dcm"))
    return dir


def seal_series(dir):
    return {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(Path(dir).glob("*.dcm"))}


def dry_run(series_dir, register_out):
    v = validate_series(series_dir)
    if v["verdict"] != "ACCEPT":
        return {"verdict": "REJECT", "reasons": v["rejects"]}
    seals = seal_series(series_dir)
    reg = {"generated": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
           "verdict": "ACCEPT", "n_slices": v["n_slices"],
           "warns": v["warns"], "has_contours": v["has_contours"],
           "seals": seals, "mode": "synthetic dry-run"}
    Path(register_out).write_text(json.dumps(reg, indent=2), encoding="utf-8")
    DRAFT.parent.mkdir(parents=True, exist_ok=True)
    DRAFT.write_text(f"""# RPT-001 v5.0 DRAFT — Real-Data Section (synthetic dry-run)

> **DRAFT**: generated by D3 dry-run on synthetic DICOM. Becomes official
> v5.0 only after real partner data (HOSPITAL-PARTNERSHIP-001).

## 1. Pipeline Integrity (dry-run)
- Validator verdict: {v['verdict']} (n_slices={v['n_slices']})
- Warns: {v['warns'] or 'none'}
- Sealed files: {len(seals)} (sha256)

## 2. Planned Real-Data Analyses
Paired DVH deltas (B2), TCP/NTCP (B3), inter-observer (CLIN-001),
aggregated per REAL-DATA-PLAYBOOK after 10 cases.

## 3. Traceability
EXPERIMENT_REPORT.md v4.0 (supersedes on approval), DOSE-IMPACT-001,
REAL-DATA-PLAYBOOK, tools/dry_run_pipeline.py.
""", encoding="utf-8")
    return {"verdict": "ACCEPT", "n_slices": v["n_slices"],
            "seals": len(seals), "draft": str(DRAFT)}


if __name__ == "__main__":
    import sys
    d = build_synthetic_series(Path(sys.argv[1]) if len(sys.argv) > 1
                               else Path("/tmp/dryrun"))
    print(json.dumps(dry_run(d, ROOT / "dry_run_register.json"), indent=2))
